In [45]:
#таблица умножения b>a, d>c
a = int(raw_input())
b = int(raw_input())
c = int(raw_input())
d = int(raw_input())
print ' \t',
for i in range(a, b):
    print i, '\t',
print
for j in range(c, d):
    print j, '\t',
    for i in range(a, b):
        print j * i, '\t',
    print 

4
6
7
9
 	4 	5 	
7 	28 	35 	
8 	32 	40 	


In [46]:
#сумма чисел на отрезке, делящихся на 3
a = int(raw_input())
b = int(raw_input())
s = 0
k = 0
for i in range (a,b+1):
    if i % 3 == 0:
        s += i
        k += 1
print s/float(k)

1
1000
501.0


In [51]:
# процентное содержание G и C
s = raw_input()
i = 0
s.upper()
j = len(s)
for x in s:
    if (x == 'G' or x == 'C'):
        i += 1
print ((float(i) / j)* 100)

adfadfsdGGGsadasdCCCC
33.3333333333


In [47]:
# aaabbbccc -> a3b3c3
s = raw_input()
i = 1
j = 1
S = ''
while (i < len(s) + 1):
    while (i < len(s) and s[i] == s[i-1]):
        j += 1
        i += 1
    S += s[i-1]+str(j)
    j = 1
    i += 1
print S

aaaaaaabbbbbcc
a7b5c2


In [ ]:
students = ['Ivan', 'Masha', 'Sasha']
students += ['Olga']
students += 'Olga'
print students

In [48]:
s = 0
a = [int(i) for i in raw_input().split()]
for i in a:
    s += i
print s

1 2 3 4 5
15


In [49]:
#ввод строки чисел, вывод строки с суммами 2 соседей
a = [int(i) for i in raw_input().split()]
b = []
j = 0
l = len(a)
if l != 1:
    for i in a:
        b.append (a[(j+1) % l] + a[(j-1) % l])
        j += 1
    for x in b:
        print x,
else: 
    print a[0]

1 2 3 4 5 6 
8 4 6 8 10 6


In [50]:
#вывод повторяющихся элементов
a = [int(i) for i in raw_input().split()]
b = []
a.sort()
for i in a:
    #print a
    j = a.count(i)
    if (j > 1):
        b.append(i)
    for k in range(j-1):
        a.remove(i)
    #print a
for x in b:
    print x,

1 1 1 1 2 2 3
1 2


In [52]:
#сапер k - мины, m x n - поле
n, m, k = (int(i) for i in raw_input().split())
a = [[0 for j in range(m)] for i in range(n)]
for i in range(k):
    row, col = (int(i) - 1 for i in raw_input().split())
    a[row][col] = -1
for i in range(n):
    for j in range(m):
        if a[i][j] == 0:
            for di in range(-1, 2):
                for dj in range(-1, 2):
                    ai = i + di
                    aj = j + dj
                    # (ai, aj)
                    if 0 <= ai < n and 0 <= aj < m and a[ai][aj] == -1:
                        a[i][j] += 1
for i in range(n):
    for j in range(m):
        if a[i][j] == -1:
            print '*',
        elif a[i][j] == 0:
            print'.',
        else:
            print a[i][j],
    print

10 10 5
5 9
4 4
2 8
7 3
7 5
. . . . . . 1 1 1 .
. . . . . . 1 * 1 .
. . 1 1 1 . 1 1 1 .
. . 1 * 1 . . 1 1 1
. . 1 1 1 . . 1 * 1
. 1 1 2 1 1 . 1 1 1
. 1 * 2 * 1 . . . .
. 1 1 2 1 1 . . . .
. . . . . . . . . .
. . . . . . . . . .


In [53]:
#считывание чисел, пока сумма не станет 0, тогда выводим сумму квадратов
i = int(raw_input())
s = i
s2 = i ** 2
while (s != 0):
    i = int(raw_input())
    s += i
    s2 += i ** 2
print s2

1
2
-2
3
-4
34


In [ ]:
#выводит n чисел из посл-ти 1223334444...
n = int(raw_input())
s = []
S = ''
i = 1
j = 0
while (j < n):
    s += [str(i)] * i
    j += i
    i += 1
for i in range(n):
    S += s[i] + ' '
print (S)

In [ ]:
#вывод позиций определенного числа в строке
a = [int(i) for i in raw_input().split()]
x = int(raw_input())
if x not in a:
    print ('Отсутствует')
while (x in a):
    ind = a.index(x)
    print ind,
    a.remove(x)
    a.insert(ind, '.')

In [ ]:
#матрица -> матрица с пересчитанными элементами
b = []
a = [i for i in raw_input().split()]
p = len(a)
j = 0
if (a[0] == 'end'):
    print b
else:
    while (a[0] != 'end'):
        b.append(a)
        j += 1
        a = [i for i in raw_input().split()]
    else:
        for k in range(j):
            for m in range(p):
                b[k][m] = int(b[k][m])
        c = [[0] * p for i in range(j)]
        for k in range(j):
            for m in range(p):
                c[k][m] = b[(k-1)%j][m] + b[(k+1)%j][m] + b[k][(m+1)%p] + b[k][(m-1)%p]
                print c[k][m],
            print   

In [55]:
#вывод в матрицу по спирали элементов от 1 до n^2
n = int(raw_input())
a = [[-1] * (n + 2) for i in range(n + 2)]
for k in range(1, n + 1):
    for m in range(1, n + 1):
        a[k][m] = 0
#for k in range(n + 2):
#    for m in range(n + 2):
#        print a[k][m], 
#    print
num = 0
row, col = 1, 0

while (num < n ** 2):
    #print "lol start"
    while (a[row][col + 1] == 0):
        num += 1
        col += 1
        a[row][col] = num 
        #print num, 
    while (a[row + 1][col] == 0):
        num += 1
        row += 1
        a[row][col] = num
        #print num,
    while (a[row][col - 1] == 0):
        num += 1
        col -= 1
        a[row][col] = num
        #print num,
    while (a[row - 1][col] == 0):
        num += 1
        row -= 1
        a[row][col] = num
        #print num,
    #print "lol"
for k in range(1, n + 1):
    for m in range(1, n + 1):
        print a[k][m],
    print

10
1 2 3 4 5 6 7 8 9 10
36 37 38 39 40 41 42 43 44 11
35 64 65 66 67 68 69 70 45 12
34 63 84 85 86 87 88 71 46 13
33 62 83 96 97 98 89 72 47 14
32 61 82 95 100 99 90 73 48 15
31 60 81 94 93 92 91 74 49 16
30 59 80 79 78 77 76 75 50 17
29 58 57 56 55 54 53 52 51 18
28 27 26 25 24 23 22 21 20 19


In [1]:
def f(x):
    if (x <= -2):
        return (1 - (x+2)**2)
    elif (-2 < x <= 2):
        return (-x/2)
    else:
        return ((x-2)**2 + 1)

10555

In [32]:
#удаляет нечетные, четные делит пополам
def modify_list(l):
    s = []
    for i in l:
        if (i % 2 == 0):
            j = i // 2
            s.append(j)
    for i in range(len(l) - 1,-1,-1):
        del l[i]
    for i in s:
        l.append(i)
lst = [1, 2, 3, 4, 5, 6]
print(modify_list(lst))  # None
print(lst)               # [1, 2, 3]
modify_list(lst)
print(lst) 

lst = [10, 5, 8, 3]
modify_list(lst)
print(lst)   

None
[1, 2, 3]
[1]
[5, 4]


In [38]:
#Напишите функцию update_dictionary(d, key, value), которая принимает на вход словарь d и два числа: key и value.
#если ключ есть, то добавить, иначе добавить в 2*key
def update_dictionary(d, key, value):
    if key in d:
        d[key] += [value]
    elif 2*key in d:
        d[2*key] += [value]
    else:
        d[2*key] = [value]

d = {}
print(update_dictionary(d, 1, -1))  # None
print(d)                            # {2: [-1]}
update_dictionary(d, 2, -2)
print(d)                            # {2: [-1, -2]}
update_dictionary(d, 1, -3)
print(d)                            # {2: [-1, -2, -3]}

None
{2: [-1]}
{2: [-1, -2]}
{2: [-1, -2, -3]}


In [49]:
#вывести распределение слов в строке (без учета регистра)
a = [i for i in raw_input().split()]
b = []
d = {}
for i in a:
    b.append(i.lower())
for i in b:
    if i in d:
        d[i] += 1
    else:
        d[i] = 1
for key, value in d.items():
    print key, value

AAA aaa aAa aaaaa
aaaaa 1
aaa 3


In [60]:
def f(x):
    return x**2
n = int(raw_input())
d = {}
s = []
for i in range(n):
    x = int(raw_input())
    s.append(x)
    if x not in d:
        d[x] = f(x)
for i in s:
    print d[i]


3
1
2
2
1
4
4


In [23]:
#расшифровать a2b3c4 = aabbbcccc
with open('dataset_3363_2.txt') as inf:
    s = inf.readline().strip()
#s = 'a10b4c2d20'
l = len(s)
j = ''
res = ''
k = 0
d = {'0','1','2','3','4','5','6','7','8','9'}
for i in range(1, l):
    if s[i] in d:
        j += s[i]
        k += 1
    else:
        res += s[i - k - 1] * int(j)
        j = ''
        k = 0
res += s[l - k - 1] * int(j)
with open('out.txt', 'w') as out:
    out.write(res)


In [44]:
#самое часто встречающееся слово
#s = 'ccCc bbb Cccc aaa aaa cccC bbbb bbbb bbbb'
s = ''
with open ('dataset_3363_3.txt') as inf:
    for line in inf:
        line = line.strip()
        s += (line + ' ')
#print s
d = {}
j = ''
i = 0
l = len(s)
for i in range(l):
    if (s[i] != ' '):
        j += s[i].lower()
        i += 1
    else:
        if j in d:
            d[j] += 1
        else:
            d[j] = 1
        j = ''
        i += 1
if j in d:
    d[j] += 1
else:
    d[j] = 1
m = 0
win = ''
for key in d:
    if (d[key] > m) or (d[key] == m and key < win):
        m = d[key]
        win = key
with open('out.txt', 'w') as out:
    out.write(win+' '+str(m))

In [73]:
#посчитать средние баллы по предметам и по ученикам
math, phys, rus = 0, 0, 0
s = []
h = 0
with open ('dataset_3363_4.txt') as inf:
    for line in inf:
        line = line.strip().split(';')
        s += [line]
        h += 1
#print s
with open('out.txt', 'w') as out:
    for k in range (h):
        math += float(s[k][1])
        phys += float(s[k][2])
        rus += float(s[k][3])
        out.write (str((float(s[k][1]) + float(s[k][2]) + float(s[k][3])) / 3) + '\n')
    #print math, phys, rus
    out.write (str(math / h) + ' ' + str(phys / h) + ' ' + str(rus / h))

In [1]:
import math as m
r = float(raw_input())
print (2*m.pi*r)

1
6.28318530718


In [2]:
import sys
for k in range (1, len(sys.argv)):
    print sys.argv[k]

-f
/run/user/1000/jupyter/kernel-0ac2e7f6-744a-4b4f-9403-ed1993542afb.json


In [ ]:
#посчитать кол-во строк в файле по ссылке
import requests as req
l = ''
r = req.get('https://stepic.org/media/attachments/course67/3.6.2/626.txt')
l = r.text
print l.count('\n')

In [ ]:
#Имеется набор файлов, каждый из которых, кроме последнего, содержит имя следующего файла. 
#Первое слово в тексте последнего файла: "We".
#Скачайте предложенный файл. В нём содержится ссылка на первый файл из этого набора. 
import requests as req
l = ''
r = req.get('https://stepic.org/media/attachments/course67/3.6.3/699991.txt')
l = r.text
while (l[:2] != 'We'):
	url = 'https://stepic.org/media/attachments/course67/3.6.3/' + l.strip()
	print url
	q = req.get(url)
	l = q.text
print l

In [34]:
#вывести таблицу чемпионата по результатам
import numpy as np
n = int(raw_input())
game = []
teams = {}
final = {}
point = []
for i in range(n):
    game = [j for j in raw_input().split(';')]
    if game[0] not in teams:
        teams[game[0]] = [0,0,0,0,0]
    if game[2] not in teams:
        teams[game[2]] = [0,0,0,0,0]
    if (int(game[1]) > int(game[3])):
        teams[game[0]] = list(np.array(teams[game[0]]) + np.array([1,1,0,0,3]))
        teams[game[2]] = list(np.array(teams[game[2]]) + np.array([1,0,0,1,0]))
    if (int(game[1]) == int(game[3])):
        teams[game[0]] = list(np.array(teams[game[0]]) + np.array([1,0,1,0,1]))
        teams[game[2]] = list(np.array(teams[game[2]]) + np.array([1,0,1,0,1]))
    if (int(game[1]) < int(game[3])):
        teams[game[0]] = list(np.array(teams[game[0]]) + np.array([1,0,0,1,0]))
        teams[game[2]] = list(np.array(teams[game[2]]) + np.array([1,1,0,0,3]))
    i = i + 1
for key in teams:
    if teams[key][4] not in point:
        point.append(teams[key][4])
point.sort()
point.reverse()
for i in point:
    for key in teams:
        if (teams[key][4] == i):
            print key, ':', teams[key][0], teams[key][1], teams[key][2], teams[key][3], teams[key][4]

3
cska;2;loko;3
cska;1;zenit;1
loko;2;zenit;1
loko : 2 2 0 0 6
cska : 2 0 1 1 1
zenit : 2 0 1 1 1


In [40]:
#зашифровать/расшифровать
alph = raw_input()
code = raw_input()
x1 = raw_input()
y1 = raw_input()
x2 = ''
y2 = ''
d1 = {}
d2 = {}
for i in range(len(alph)):
    d1[alph[i]] = code[i]
    d2[code[i]] = alph[i]
for i in x1:
    if i in d1:
        x2 += d1[i]
for i in y1:
    if i in d2:
        y2 += d2[i]
print x2 
print y2

abc
cba
abcabc
ccc
cbacba aaa


In [49]:
#вывод слов, которых нет в словаре
n = int(raw_input())
d1 = set()
d2 = set()
line = []
for i in range(n):
    d1.add(raw_input().lower())
m = int(raw_input())
for i in range(m):
    line += raw_input().split()
    for j in line:
        d2.add(j.lower())
for i in (d2-d1):
    print i, 

3
abc
abd
abe
2
abc dfh efh
JFHEUFH
efh dfh jfheufh


In [ ]:
#куда перейдет объект
n = int(raw_input())
comm = []
x, y = 0, 0
for i in range (n):
    comm = [j for j in raw_input().split()]
    if comm[0] == 'север':
        y += int(comm[1])
    elif comm[0] == 'юг':
        y -= int(comm[1])
    elif comm[0] == 'за':
        y -= int(comm[1])
    elif comm[0] == 'юг':
        y -= int(comm[1])

In [23]:
#вывести средний рост по классам
height = {}
s = []
n = 0
h = 0
for i in range(1,12):
    height[i] = '-'
with open ('dataset_3380_5.txt') as inf:
    for line in inf:
        line = line.strip().split('\t')
        s += [line]
for i in range(1,12):
    for line in s:
        #print line[1]
        if int(line[0]) == i:
            n += 1
            h += float(line[2])
    if n != 0:
        height[i] = h / n
    n = 0
    h = 0
for i in height:
    print (str(i) + ' ' + str(height[i]))

1 126.428571429
2 130.384615385
3 135.5
4 140.8
5 146.166666667
6 154.230769231
7 161.5
8 166.333333333
9 171.0
10 170.333333333
11 174.6


In [6]:
from numpy import *
b = arange(12).reshape(4,3)
print b

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
